// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXKvqmpMh-7V-hHYceApnXavruvvmjo78',
    appId: '1:724051451512:web:ea080bfd6e1b099749978d',
    messagingSenderId: '724051451512',
    projectId: 'fir-d2b85',
    authDomain: 'fir-d2b85.firebaseapp.com',
    storageBucket: 'fir-d2b85.appspot.com',
    measurementId: 'G-YJ5RL0H1D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8bfgVDaZI7CCWEuFkoNswqVEqNcFNaoA',
    appId: '1:724051451512:android:54c52d611f4b91f849978d',
    messagingSenderId: '724051451512',
    projectId: 'fir-d2b85',
    storageBucket: 'fir-d2b85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABgQ9fUvxPiQ79onKKR0pu6ABq9tq52Ww',
    appId: '1:724051451512:ios:8b9af639cbca59b849978d',
    messagingSenderId: '724051451512',
    projectId: 'fir-d2b85',
    storageBucket: 'fir-d2b85.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
